USE master
GO
IF DB_ID('GestionMecanica') IS NOT NULL
	DROP DATABASE GestionMecanica;
GO
CREATE DATABASE GestionMecanica
GO

USE GestionMecanica;

CREATE TABLE Especialidad(
		ID int IDENTITY(1,1) NOT NULL,
		Nombre varchar(100) NOT NULL UNIQUE,
		CONSTRAINT PK_Especialidad PRIMARY KEY (ID)
);
GO

CREATE TABLE Roles (
	--Roles
	id INT IDENTITY(1,1) NOT NULL,
	Nombre NVARCHAR(20) NOT NULL UNIQUE,
	CONSTRAINT Pk_Rol PRIMARY KEY(id)
);
GO

CREATE TABLE Usuario (
	--Usuario
	ID INT IDENTITY(1,1),
	Nombre VARCHAR(100) NOT NULL,
	Email VARCHAR(100) NOT NULL UNIQUE,
	Pwd VARCHAR(100)NOT NULL,
	RolID int NOT NULL,

	--Cliente
	Telefono NVARCHAR(20) NULL,
	Diereccion NVARCHAR(200)NULL,
	Ciudad NVARCHAR(100)NULL,
	Estado NVARCHAR(100)NULL,
	CodigoPostal NVARCHAR(20)NULL,
	Pais NVARCHAR(50)NULL,

	--Administrador
	Area NVARCHAR(100)NULL,

	--Mecanico
	EspecialidadID INT Null,

	--Extras
	Activo BIT NOT NULL DEFAULT 1,
	FechaRegistro DATETIME DEFAULT GETDATE()
	
	CONSTRAINT PK_Usuario PRIMARY KEY (ID)
	CONSTRAINT FK_Usuarios_Roles FOREIGN KEY (RolID) REFERENCES Roles(Id),
	CONSTRAINT chk_rol CHECK (Rol IN ('Cliente', 'Administrador', 'Mecanico')),
	CONSTRAINT FK_Especialidad_Mecanico FOREIGN KEY (EspecialidadID) REFERENCES Especialidad(ID),
);
GO

CREATE TABLE Marca (
	ID INT IDENTITY(1,1) NOT NULL,
	Nombre VARCHAR(100) NOT NULL,
	CONSTRAINT PK_MarcaID PRIMARY KEY (ID)
);
GO

CREATE TABLE Modelo (
	ID INT IDENTITY(1,1) NOT NULL,
	Modelo VARCHAR(100) NOT NULL,
	MarcaID INT NOT NULL
	CONSTRAINT PK_ModeloID PRIMARY KEY(ID),
	CONSTRAINT FK_MarcaModelo FOREIGN KEY (MarcaID) REFERENCES Marca(ID)
);
GO

CREATE TABLE Vehiculo(
	Patente NVARCHAR(10),
	ClienteID INT NOT NULL, 
	ModeloID INT NOT NULL,
	Anio INT NOT NULL CHECK(Anio BETWEEN 1900 AND YEAR(GETDATE())),
	CONSTRAINT Pk_VehiculoID PRIMARY KEY(PATENTE),
	CONSTRAINT FK_VehiculoID_ModeloID FOREIGN KEY (ModeloID) REFERENCES Modelo(ID),
	CONSTRAINT FK_VEhiculo_Cliente FOREIGN KEY (ClienteID) REFERENCES Usuario(ID)
);
GO

CREATE TABLE Repuesto(
	ID INT IDENTITY(1,1) NOT NULL,
	Nombre VARCHAR(100) NOT NULL,
	Stock INT NOT NULL,
	Precio DECIMAL(18,2) NOT NULL,
	CONSTRAINT PK_Repuesto PRIMARY KEY (ID)
);
GO

CREATE TABLE Reparacion(
	ID INT IDENTITY(1,1) NOT NULL,
	Descripcion VARCHAR(MAX),
	Fecha DATETIME,
	CONSTRAINT PK_Reparacion PRIMARY KEY (ID)
);
GO

CREATE TABLE Estado(
	ID INT IDENTITY(1,1) NOT NULL,
	Estado VARCHAR(20) CHECK (Estado IN ('Pendiente', 'Iniciado', 'Finalizado')),
	CONSTRAINT PK_Estado PRIMARY KEY (ID)
);
GO

CREATE TABLE Orden(
	ID INT IDENTITY(1,1) NOT NULL, 
	FechaIngreso DATETIME NOT NULL,
	VehiculoID INT NOT NULL,
	EstadoID INT not null,
	DetalleOrden VARCHAR(max) Not null,
	ReparacionID INT,
	FechaEntregaEst DATETIME, 
	CONSTRAINT PK_Orden PRIMARY KEY (ID),
	CONSTRAINT FK_Reparacion_Orden FOREIGN KEY (ReparacionID) REFERENCES Reparacion(ID),
	CONSTRAINT FK_Estado_Orden FOREIGN KEY (EstadoID) REFERENCES Estado(ID)
);
GO

CREATE TABLE DetalleOrden (
	ID INT IDENTITY(1,1) not null,
	RepuestoID INT NOT NULL,
	Cantidad INT NOT NULL,
	SubTotal DECIMAL (18,2) NOT NULL,
	OrdenID INT NOT NULL,
	CONSTRAINT PK_DetalleOrden PRIMARY KEY (ID),
	CONSTRAINT FK_Repuesto_DetalleOrden FOREIGN KEY (RepuestoID) REFERENCES REPUESTO(ID),
	CONSTRAINT FK_DetalleOrden_Orden FOREIGN KEY (OrdenID) REFERENCES Orden(ID)
);
GO

CREATE TABLE ORDEN_MECANICO(
	OrdenID INT NOT NULL,
	MecanicoID INT NOT NULL,
	CONSTRAINT PK_OrdenMecanico PRIMARY KEY (OrdenID, MecanicoID),
	CONSTRAINT FK_Orden_OrdenMecanico FOREIGN KEY (OrdenID) REFERENCES Orden(ID),
	CONSTRAINT FK_Mecanico_OrdenMecanico FOREIGN KEY (MecanicoID) REFERENCES Usuario(ID)
);
GO

CREATE TABLE Factura(
	ID INT IDENTITY(1,1) NOT NULL,
	OrdenID INT NOT NULL,
	Total DECIMAL(18,2) NOT NULL,
	FechaDeEmision DATETIME NOT NULL,
	EstadoID INT NOT NULL, 
	Pagada BIT DEFAULT 0,
	CONSTRAINT PK_Factura PRIMARY KEY(ID),
	CONSTRAINT FK_Estado FOREIGN KEY(EstadoID) REFERENCES Estado(ID)
);
GO

CREATE TABLE MetodoPago(
	ID INT IDENTITY(1,1) NOT NULL,
	Metodo VARCHAR(100)
	CONSTRAINT PK_MetodoPago PRIMARY KEY (ID)
);
GO

CREATE TABLE Pago (
	ID INT IDENTITY(1,1) NOT NULL,
	FacturaID INT NOT NULL,
	MontoTotal DECIMAL(18,2) NOT NULL,
	FechaPago DATETIME NOT NULL,
	MetodoPagoID INT NOT NULL,
	CONSTRAINT PK_Pago PRIMARY KEY (ID),
	CONSTRAINT FK_Factura_PAGO FOREIGN KEY (FacturaID) REFERENCES Factura(ID),
	CONSTRAINT FK_MetodoPago_PAGO FOREIGN KEY (MetodoPagoID) REFERENCES MetodoPago(ID)
);
GO